INSERT INTO PUBLIC.MPA (ID,NAME)
	VALUES (1,'G');
INSERT INTO PUBLIC.MPA (ID,NAME)
	VALUES (2,'PG');
INSERT INTO PUBLIC.MPA (ID,NAME)
	VALUES (3,'PG-13');
INSERT INTO PUBLIC.MPA (ID,NAME)
	VALUES (4,'R');
INSERT INTO PUBLIC.MPA (ID,NAME)
	VALUES (5,'NC-17');

INSERT INTO PUBLIC.GENRE (ID,NAME)
    VALUES (1,'Комедия');
INSERT INTO PUBLIC.GENRE (ID,NAME)
    VALUES (2,'Драма');
INSERT INTO PUBLIC.GENRE (ID,NAME)
    VALUES (3,'Мультфильм');
INSERT INTO PUBLIC.GENRE (ID,NAME)
    VALUES (4,'Триллер');
INSERT INTO PUBLIC.GENRE (ID,NAME)
    VALUES (5,'Документальный');
INSERT INTO PUBLIC.GENRE (ID,NAME)
    VALUES (6,'Боевик');